name: serialization-transformer-serialization-test
version: 0.0.1
description: Testing serialization with Serialization using Code generation by transformer.
dependencies:
  serialization: ">=0.10.3 <0.11.0"
transformers:
- serialization:
    $include: ["bin/test.dart"]
