name: dartson-transformer-serialization-test
version: 0.0.1
description: Testing serialization with Dartson using Code generation by transformer.
dependencies:
  dartson: ">=0.2.0 <0.3.0"
transformers:
- dartson
